version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - sqlserver

sqlserver:
  image: mcr.microsoft.com/mssql/server:2022-latest
  platform: linux/amd64  
  environment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: "RayoCinema3!"
  ports:
    - "1433:1433"

